version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    reviewers:
      - 'robinlahtinen'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    reviewers:
      - 'robinlahtinen'
  - package-ecosystem: 'composer'
    directory: '/'
    schedule:
      interval: 'daily'
    reviewers:
      - 'robinlahtinen'
